language: node_js
node_js:
- node
deploy:
  provider: heroku
  api_key:
    secure: iFf4loEAnAC0dL86//omBg2FOQKYcz7QtGWl26jBDlWHAHjrfDXw5BTedddr7HT5sNRx13KEAYIFMl2sewLnLIM5n3XNMtaLd5nKSmggIRn6FHDCGd/JHolcNtIhDEHWyO+r6ZvyAolginy3qccXMOdTQ8HwjFnX324DhoS0FSqRHwitSO/52J+KhuX6y0DZOdXwlDaA6sXztS64fH37EPVrzZEOAXY82MG042ksTeNzXZiuH4w0vXb2Do6EG0b5eVc6Dx/YDGlPOgqLvDKKfcgieNjR9bE9NNSrMfXHVHaM8S6YZLfCBOVRWJ9oGoqqr5aptHJHqw96XceBfrNMOKLrrl+NtMantEZsCk0b7LjipW4ATYBd3zWPOZ9HeoVKqhNXOKlT+sGTbvPkUnL4NpnsJD1jm1MY0sIOaMA5RCHqGIt11EMtELVAGNDUwx4Nam3ywxZbqo1aiYjsDtahawYDYeAMbzc/WiPAPDvTgRW3rH7sIzADX4pHneTinxJE8bg0HoGOfheRH5leN5E6XXRZgX6758khbl2cBUq4CWNCZB/1piR+AmzvZ9XpmtXc3TEX90/VCd+YgXzlHpLfzalxVC9s59sVuXo9P+jv5l0/fo3ouUdillSnZlKcwAq9Prb/+7Vf54CiVraZOU/JSdD8gdjae6wYT5lnkq2+IhQ=
  app: Technical-Assessment
  on: production
